# Generated by Django 4.0.1 on 2022-01-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=25)),
                ('pic_format', models.CharField(max_length=5)),
                ('uploaded_picture', models.ImageField(upload_to='static/')),
                ('width', models.DecimalField(decimal_places=3, max_digits=5)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
            ],
        ),
    ]
